# https://Taskfile.dev

version: 3

tasks:
  build:prez-ui:
    desc: Build prez-ui static files
    dir: prez-ui
    cmds:
      - pnpm generate
    sources:
      - prez-ui
    generates:
      - prez-ui/.output/public

  deploy:
    dir: deploy
    cmds:
      - uv run ansible-playbook playbook.yml
